version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: stripe/stripe-php
    versions:
    - 7.69.0
    - 7.70.0
    - 7.72.0
    - 7.73.0
    - 7.74.0
    - 7.75.0
    - 7.76.0
  - dependency-name: sylius-labs/coding-standard
    versions:
    - 4.0.1
  - dependency-name: sylius/sylius
    versions:
    - 1.9.0
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.70
    - 0.12.71
    - 0.12.73
  - dependency-name: phpstan/phpstan-webmozart-assert
    versions:
    - 0.12.10
    - 0.12.11
    - 0.12.9
