# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: config_test.yml }

framework:
    router: { resource: '%kernel.project_dir%/app/config/routing_test_cached.yml' }

doctrine:
    orm:
        entity_managers:
            default:
                metadata_cache_driver:
                    type: memcached
                    host: localhost
                    port: 11211

twig:
    strict_variables: true

sylius_channel:
    debug: true

fos_rest:
    exception:
        debug: true

doctrine_migrations:
    dir_name: '%kernel.project_dir%/vendor/sylius/sylius/app/migrations'
