# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: "config.yml" }

parameters:
    currency: USD
    locale: en_US

framework:
    test: ~
    default_locale: "en"
    session:
        storage_id: session.storage.mock_file

doctrine:
    dbal:
        dbname: "%database_name%_test"
        driver_class: Sylius\Bundle\CoreBundle\Test\MySqlDriver

doctrine_cache:
    providers:
        sylius_settings:
            type: array

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error

payum:
    gateways:
        paypal_express_checkout:
            factory: paypal_express_checkout
            payum.http_client: "@sylius.payum.http_client"
            username: TEST
            password: TEST
            signature: TEST
            sandbox: true
        credit_card:
            factory: stripe_checkout
            secret_key: EDITME
            publishable_key: EDITME
            payum.template.layout: SyliusShopBundle::Checkout/layout.html.twig
            payum.template.obtain_token: SyliusPayumBundle::Action/Stripe/obtainCheckoutToken.html.twig

swiftmailer:
    disable_delivery: true
    logging: true
    spool:
        type: file
        path: "%kernel.cache_dir%/spool"

sylius_payment:
    gateways:
        cc: Credit Card
        test: Test
        stripe: Stripe
        paypal_express_checkout: Paypal Express Checkout

sylius_theme:
    sources:
        test: ~

twig:
    exception_controller: "Sylius\\Bundle\\CoreBundle\\Controller\\VerboseExceptionController::showAction"
