sylius_api:
    resource: "@SyliusApiBundle/Resources/config/routing/main.yml"
    prefix: /api

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

sylius_web:
    resource: "@SyliusWebBundle/Resources/config/routing/main.yml"
