name: Build Docker Image

on:
    push:
        branches-ignore:
            - master
        paths-ignore:
            - "*.md"
    pull_request:
        paths-ignore:
            - "*.md"

jobs:
    build-image:
        strategy:
            matrix:
                platform: [linux/amd64,linux/arm64]
        
        runs-on: ubuntu-latest
        steps:
            -
                name: Set Up QEMU
                uses: docker/setup-qemu-action@v1
            -
                name: Set Up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Build Image
                uses: docker/build-push-action@v2
                with:
                    push: false
                    platforms: ${{ matrix.platform }}
                    cache-from: type=gha
                    cache-to: type=gha
